//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIO3_BanDuocPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int IDDANHGIA { get; set; }
        public Nullable<int> IDSP { get; set; }
        public Nullable<int> IDTV { get; set; }
        public Nullable<decimal> DIEMDANHGIA { get; set; }
        public string BINHLUAN { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
