//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIO3_BanDuocPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.DANHGIAs = new HashSet<DANHGIA>();
        }
    
        public int IDSP { get; set; }
        public Nullable<int> IDLOAISP { get; set; }
        public Nullable<int> IDNCC { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<System.DateTime> NGAYSX { get; set; }
        public Nullable<System.DateTime> HANSD { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> SOLANMUA { get; set; }
        public Nullable<decimal> DIEMDANHGIATB { get; set; }
        public Nullable<int> LUOTBINHLUAN { get; set; }
        public string HINHANH { get; set; }
        public string MOTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
